version: '3'

services:
  app:
    build: .
    container_name: foo-app-container
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails assets:precompile  && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - public-data:/teshioni_order_admin/public
      - tmp-data:/teshioni_order_admin/tmp
      - log-data:/teshioni_order_admin/log
    ports:
      - "3000:3000"
    env_file:
      - docker.rails.env
    # environment:
    #   - RAILS_ENV=production
    #   - RAILS_MASTER_KEY=e0c976bd7faed6411baee8aaf6d77c79
    #   - RAILS_SERVE_STATIC_FILES=1
    #   - DB_HOST=aa1seln4hxaucz6.cwmdpqsg3vac.ap-northeast-1.rds.amazonaws.com
    #   - DB_PORT=5432
    #   - DB_NAME=ebdb
    #   - DB_USERNAME=rails
    #   - DB_PASSWORD=password55
volumes:
  public-data:
  tmp-data:
  log-data:
