version: '3'

services:
  app:
    build: .
    container_name: foo-app-container
    command: sh -c "bundle exec rails assets:precompile  && bundle exec rails db:migrate && bundle exec puma -t 5:5 -b unix:///foo/tmp/sockets/puma.sock"
    volumes:
      - public-data:/foo/public
      - tmp-data:/foo/tmp
      - log-data:/foo/log
    env_file:
      - docker.rails.env
  web:
    build:
      context: docker_containers/nginx
    container_name: foo-web-container
    volumes:
      - public-data:/railsapp/public
      - tmp-data:/railsapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
